framgia/sph-classroom-els-fe

src/pages/student/main/Registration/index.js, src/pages/student/main/Registration/index.module.css
- https://framgiaph.backlog.com/view/E_CLASSROOM-43
- http://localhost:3003/Registration
- 
- N/A
- N/A
- N/A
s
=> E_CLASSROOM-43 [Frontend] [Student] [Markup] User Authentication 2/2

package-lock.json, package.json, public/index.html, src/components/App.js, src/components/css/QuizRightAnswerResult.css, src/components/css/Result.css, src/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css, src/pages/student/quizzes/QuizResult/index.js, src/routes/index.js, yarn.lock
- https://framgiaph.backlog.com/view/E_CLASSROOM-51
[screencapture-localhost-3003-2021-11-02-10_55_36.pdf](https://github.com/framgia/sph-classroom-els-fe/files/7457491/screencapture-localhost-3003-2021-11-02-10_55_36.pdf)
N/A
-  N/A
- http://localhost:3003/categories/:id/quizzes/:id/results
- N/A
- N/A
- N/A
[screencapture-localhost-3003-2021-11-02-10_55_36.pdf](https://github.com/framgia/sph-classroom-els-fe/files/7457504/screencapture-localhost-3003-2021-11-02-10_55_36.pdf)
[screencapture-localhost-3003-2021-11-02-10_56_09.pdf](https://github.com/framgia/sph-classroom-els-fe/files/7457507/screencapture-localhost-3003-2021-11-02-10_56_09.pdf)
=> E_CLASSROOM-51 [Frontend] [Student] [Markup] Quizzes 3/3

public/index.html, src/index.js, src/pages/student/profile/ChangePassword/index.js, src/pages/student/profile/ChangePassword/index.module.css, src/routes/index.js, yarn.lock
https://framgiaph.backlog.com/view/E_CLASSROOM-46
N/A
- the route for this is `/localhost:3003/student/profile/change-password`
N/A
- http://localhost:3003/student/profile/change-password
N/A
N/A
N/A
=> E_CLASSROOM-46 [Frontend] [Student] [Markup] User Profile 3/3

src/components/App.js, src/components/css/GlobalStyle.css, src/components/users/StudentProfile.js, src/components/users/StudentProfile.module.css, src/index.js, src/pages/student/profile/ProfileDetail/index.js, src/pages/student/profile/ProfileDetail/index.module.css, src/stylecss/GlobalStyle.css
- https://framgiaph.backlog.com/view/E_CLASSROOM-44
- http://localhost:3003/profile
- 
- N/A
- N/A
- N/A
s
=> E_CLASSROOM-44 [Frontend] [Student] [Markup] User Profile 1/3

src/components/App.js, src/components/css/GlobalStyle.css, src/index.js, src/pages/student/main/NewPassword/index.module.css, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css, src/pages/student/quizzes/QuestionList/index.js, src/pages/student/quizzes/QuestionList/index.module.css, src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js, src/routes/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-50
N/A
- N/A
- `/categories/{id}/quizzes/{id}/questions`
- N/A
- N/A
- N/A
=> Feature/e classroom 50 markup student quizzes 2/3

src/api/Quiz/index.js, src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js, src/pages/student/quizzes/QuizList/index.js, src/pages/student/quizzes/QuizList/index.module.css
https://framgiaph.backlog.com/view/E_CLASSROOM-120
- Change ":id" statistically to 1 or more
- Wait patiently due to its delay
- http://localhost:3003/categories/:id/quizzes
- N/A
- N/A
- N/A
=> E_CLASSROOM-120 [Integration] [Frontend] [Student] [Markup] Quizzes 1/2

src/api/Auth/index.js, src/pages/student/main/Registration/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-104
- docker-compose exec frontend yarn add axios
- docker-compose exec frontend yarn 
- docker-compose exec frontend yarn add react-hook-form
- http://localhost:3003/registration
- 
- N/A
- N/A
- N/A
=> E_CLASSROOM-104 [Frontend] [Student] [Integration] User Authentication 2/2

src/api/Category/index.js, src/pages/student/categories/CategoryList/index.js, src/pages/student/categories/CategoryList/index.module.css
- https://framgiaph.backlog.com/view/E_CLASSROOM-113
- [ x ] Integrate category page with the backend displaying list of categories
- N/A
- N/A
-  Login first before accesing
- N/A
s
=> E classroom 113 integration student categories

src/api/Base/index.js, src/components/Pagination/index.js, src/pages/student/categories/CategoryList/index.js, src/pages/student/main/Dashboard/index.js, src/pages/student/main/Login/index.js, src/pages/student/main/NewPassword/index.js, src/pages/student/main/PasswordReset/index.js, src/pages/student/main/Registration/index.js, src/pages/student/profile/ChangePassword/index.js, src/pages/student/profile/EditProfile/index.js, src/pages/student/profile/ProfileDetail/index.js, src/pages/student/profile/ProfileView/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js, src/pages/student/quizzes/QuestionList/index.js, src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js, src/pages/student/quizzes/QuizList/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuizResult/index.js, src/pages/student/students/StudentDetail/index.js, src/pages/student/students/StudentList/ChangeDatails/index.js, src/pages/student/students/StudentList/index.js, src/routes/middleware/AuthRoute/index.js, src/routes/middleware/StudentRoute/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-158
- yarn install
- yarn run lint
- N/A
- http://localhost:3003/categories/1/quizzes
- http://localhost:3003/categories/:id/quizzes/:id/results
- http://localhost:3003/categories/1/quizzes/1/results/:id/answer-result
- http://localhost:3003/categories/1/quizzes/1/results/:id/answer-result#answer
- http://localhost:3003/login
- http://localhost:3003/reset-password
- http://localhost:3003/registration
- http://localhost:3003/new-password
- http://localhost:3003/categories/:id/quizzes/:id/questions
- http://localhost:3003/categories/:id/quizzes/:id/questions/:id/answer
- http://localhost:3003/categories/:id/quizzes/:id/questions/:id/answer#answer
N/A
N/A
N/A
=> E_CLASSROOM-158 [FE][Linters] Fix Linter errors

src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js, src/pages/student/categories/CategoryDetail/index.js, src/pages/student/main/Registration/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-159
N/A
- 
- http://localhost:3003/registration
N/A
N/A
N/A
=> E_CLASSROOM-159 [Bugfix] [Student] Error at Registration Page

package-lock.json, src/api/Question/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js, src/pages/student/quizzes/QuestionList/index.js, src/pages/student/quizzes/QuizList/index.js, src/pages/student/students/StudentList/ChangeDatails/index.js, src/routes/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-121
- N/A
- Change the ":Id" manually
- http://localhost:3003/categories/1/quizzes/1/questions
- N/A
- N/A
- N/A
=> E_CLASSROOM-121 [Integration] [Frontend] [Student] Quiz Questions

src/api/Category/index.js, src/api/Quiz/index.js, src/components/Pagination/index.js, src/components/Pagination/index.module.css, src/pages/student/quizzes/QuizList/index.js, src/pages/student/quizzes/QuizList/index.module.css
Note: Consider the following for pagination:
- Current Page
- PerPage Items
- Total Items
N/A
- Please create more quizzes to test the Pagination Functionality.
- Please wait for a couple of seconds when changing a page, It takes time for the quizzes to load when changing a page.
- http://localhost:3003/categories/1/quizzes
PAGE 1 OF QUIZZES
PAGE 2 OF QUIZZES
NO RESULTS FOUND
=> E_CLASSROOM-138 [Integration] [Student] Quiz List Pagination

src/pages/student/main/Login/index.js, src/pages/student/main/Login/index.module.css, src/pages/student/main/NewPassword/index.js, src/pages/student/main/NewPassword/index.module.css, src/pages/student/main/PasswordReset/index.js, src/pages/student/main/PasswordReset/index.module.css, src/pages/student/main/Registration/index.js, src/pages/student/main/Registration/index.module.css, src/styles/index.css
https://framgiaph.backlog.com/view/E_CLASSROOM-151
N/A
- N/A
- http://localhost:3003/login
- http://localhost:3003/registration
- http://localhost:3003/reset-password
- http://localhost:3003/new-password
N/A
N/A
=> E_CLASSROOM-151 [Improvement] [Student] Update UI for student pages 1/6

src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js, src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css, src/pages/student/categories/CategoryDetail/index.js, src/pages/student/categories/CategoryList/index.js, src/pages/student/categories/CategoryList/index.module.css, src/pages/student/quizzes/QuestionList/index.js, src/pages/student/students/StudentList/ChangeDatails/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-142
- `docker-compose restart`
- After you migrated the seed please restart the docker
- Wait for the delay, please be patient (bow)
- N/A
- N/A
=> E_CLASSROOM-142 [Integration] [Student] Subcategories Page

src/api/Answer/index.js, src/api/QuizTaken/index.js, src/pages/student/main/Login/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css, src/pages/student/quizzes/QuestionList/index.js, src/pages/student/quizzes/QuizResult/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-143
N/A
- 
- http://localhost:3003/categories/1/quizzes/1/questions
=> E_CLASSROOM-143 [Integration] [Student] [Backend] [Frontend] Taking Student Quizzes

src/pages/student/profile/EditProfile/index.js, src/pages/student/profile/EditProfile/index.module.css, src/pages/student/profile/ProfileDetail/index.js, src/pages/student/profile/ProfileDetail/index.module.css, src/pages/student/profile/ProfileView/index.js, src/pages/student/profile/ProfileView/index.module.css
https://framgiaph.backlog.com/view/E_CLASSROOM-153
Definition of Done
N/A
- N/A
- http://localhost:3003/profile
- http://localhost:3003/profile/view
- http://localhost:3003/profile/edit
-
N/A
N/A
N/A
=> E_CLASSROOM-153 [Improvement] [Student] Update UI for student pages 3/6

src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js, src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css, src/pages/student/categories/CategoryDetail/index.js, src/pages/student/categories/CategoryDetail/index.module.css, src/pages/student/categories/CategoryList/index.js, src/pages/student/categories/CategoryList/index.module.css
- https://framgiaph.backlog.com/view/E_CLASSROOM-154
Update the UI on these pages based on standard figma layout:
- http://localhost:3003/categories/1/sub
- 
- N/A
- N/A
- N/A
=> Feature/e classroom 154 improvement student update UI for student pages markup

src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css, src/pages/student/categories/CategoryDetail/index.module.css, src/pages/student/categories/CategoryList/index.module.css, src/pages/student/quizzes/QuizList/index.js, src/pages/student/quizzes/QuizList/index.module.css
- https://framgiaph.backlog.com/view/E_CLASSROOM-163
- http://localhost:3003/categories/1/sub
- http://localhost:3003/categories/1/quizzes
- 
- N/A
- N/A
- N/A
=> E_CLASSROOM-163 [Frontend] Pagination position

src/pages/student/categories/CategoryDetail/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js, src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css, src/pages/student/quizzes/QuestionList/index.js, src/pages/student/quizzes/QuestionList/index.module.css, src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js, src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.css, src/pages/student/quizzes/QuizList/index.js, src/pages/student/quizzes/QuizList/index.module.css, src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css, src/pages/student/quizzes/QuizResult/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-155
N/A
- N/A
- http://localhost:3003/categories/1/sub
- http://localhost:3003/categories/1/quizzes
- http://localhost:3003/categories/1/quizzes/1/questions
- then start quiz
N/A
N/A
N/A`
=> [Improvement] [Student] Update UI for student pages 5/6

src/pages/student/students/StudentList/index.js, src/pages/student/students/StudentList/index.module.css, src/styles/index.css
https://framgiaph.backlog.com/view/E_CLASSROOM-178
N/A
- N/A
- http://localhost:3003/students
N/A
N/A
N/A
=> E_CLASSROOM-178 [FE] [Markup] [Student] Student List Page

src/pages/student/students/StudentDetail/index.js, src/pages/student/students/StudentDetail/index.module.css, src/routes/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-185
N/A
-N/A
- http://localhost:3003/students/details
N/A
N/A
N/A
=> E_CLASSROOM-185 [FE] [Markup] [Student] Student Detail Page

src/api/Student/index.js, src/pages/student/students/StudentList/index.js, src/pages/student/students/StudentList/index.module.css
https://framgiaph.backlog.com/view/E_CLASSROOM-195
N/A
- You can search through the list of `All Students`, `Followed Students`, or through the list of `Followers`. 
- You can only search the student/s that you've followed under the list of Followed Students, the same goes for the followers. 
- If you want to search for any student/s regardless if you follow them or they follow you, you can do it under the list of All Students.
- The value of the searched student/s will retain even if you filter the list, it will only be erased if you do so, by the time you erase the search input it should return back to the original list (depending on whether All, Followed, or Followers Student List). 
- It should say `No Results Found` when no student/s was found that matched the searched value under …
=> E_CLASSROOM-195 [FE] [Integration] Student-List-Page-Search-Functionality

src/pages/student/main/Dashboard/components/FriendsActivities/index.js, src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css, src/pages/student/profile/ProfileDetail/index.js, src/pages/student/profile/ProfileDetail/index.module.css, src/pages/student/profile/ProfileView/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js, src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css, src/pages/student/students/StudentDetail/index.js, src/pages/student/students/StudentList/index.js
https://framgiaph.backlog.com/view/E_CLASSROOM-162
N/A
- This is 100% view in my end
- http://localhost:3003
- http://localhost:3003/students?page=1&filter=&search=
- http://localhost:3003/students/1
- http://localhost:3003/profile
- http://localhost:3003/profile/view
- http://localhost:3003/categories/1/quizzes/1/questions
N/A
N/A
N/A
=> E_CLASSROOM-162 [Improvement] [Markup] Icons Update
